INSERT INTO plant_information (plant_name, scientific_name, details, plant_type, maintenance_level, water_requirements, light_conditions, image_url)
VALUES
  ('ZZ Plant', 'Zamioculcas zamiifolia', 'The ZZ Plant is characterized by its thick waxy green leaves. It is a great air purifying option that can tolerate low light, making it a perfect plant for beginners.  Zamioculcas zamiifolia, affectionately called the ZZ plant or Zanzibar Gem, is a tropical plant in the aroid family, Araceae. It is native to Zanzibar, Kenya, and Eastern Africa. You might spot large potato-like rhizomes under the surface of its potting mix. Having evolved in drier conditions than most other aroids, these plants have evolved rhizomes that store water to help the ZZ plant survive drought in its natural environment. The rhizomes are actually underground stems, and what you see above ground are the stems leaves. Using these underground rhizomes, the plant slowly creeps over time to new locations, spawning new aboveground leaves along the way.', 'Succulent', 1, 4, 1,	'https://images.unsplash.com/photo-1566935712200-7de0214f5022?ixlib=rb-1.2.1&auto=format&fit=crop&w=675&q=80'),
  ('Snake Plant', 'Sansevieria trifasciata Laurentii', 'The Snake Plant Laurentii is a succulent plant characterized by its upright sword like leaves with vibrant yellow edges.  Native to southern and central Africa, the Sansevieria trifasciata Laurentii is a cultivar of snake plant with yellow variegated edges. Snake plants are tropical plants that are also succulents. Often positioned as low light plants, they are actually medium to bright light plants that tolerate, but not thrive in low light. Like other succulent plants, they have a modified form of photosynthesis, where in order to preserve water, the plant opens its pores exclusively at night. However, since photosynthesis only happens with daylight, the plant stores carbon dioxide acquired at night for use during the day, and releases oxygen (one of the end products of photosynthesis) at night when the pores open. This helps it to maximize efficiency in cleaning the air, as found in study conducted by NASA.', 'Succulent', 1, 4, 2, 'https://images.unsplash.com/photo-1588709983192-3852c7713145?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1834&q=80'),
  ('Monstera', 'Monstera deliciosa', 'The Monstera deliciosa is famous for its quirky natural leaf holes. A vibrant green beauty, it can give any interior space instant jungle vibes, and only gets better with time.  Monstera deliciosa is a species of evergreen tropical vine that is a part of Araceae, the aroid family. Native to the Tropical Americas, it is one of the few aroids which produces edible fruit, hence the species epithet deliciosa. However, it is incredibly rare that a Monstera will flower or produce fruit indoors. Instead, this plant is famous for its beautiful broad green leaves with natural leaf-holes, called fenestrations, which have led to the rise of its nickname, swiss cheese plant. These holes are theorized to maximize sun fleck capture on the forest floor by increasing the spread of the leaf while decreasing the mass of leaf cells to support.', '', 2, 3, 3, 'https://images.unsplash.com/photo-1525498128493-380d1990a112?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=675&q=80'),
  ('Fiddle Leaf Fig', 'Ficus lyrata', 'The Fiddle Leaf Fig is famous for its broad, vibrant green leaves with prominent veining. It prefers a stable environment and can be fickle when temps fluctuate. Keep it in bright light, and water about once every 1-2 weeks. The Fiddle Leaf Fig (Ficus lyrata) is a species of fig tree native to the lowland tropics of western Africa. In its native habitat, it can grow over forty feet tall, however indoor fiddle leaf figs are significantly smaller. Their leaves vary in shape but are often broad, leathery in texture, and a vibrant green hue with prominent veining. Some say they resemble a fiddle – hence their name. The fiddle leaf fig is most happy in a stable environment temperature-wise where it receives at least a few hours of bright direct light a day. They can be fickle with temperature and light changes, so consistency is key.', 'Tree', 4, 3, 4, 'https://images.unsplash.com/photo-1592829848755-55d2f17574d3?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=675&q=80'),
  ('String of Pearls', 'Senecio rowleyanus', 'This creeping, perennial succulent was named by British botanist Gordon Douglas Rowley, It is a flowering plant in the daisy family and one of our favorite low maintenance houseplant varieties to add to your indoor garden. A fast grower and easy to propagate.', 'Succulent', 4, 4, 1, 'https://s7d1.scene7.com/is/image/terrain/58123605_000_a'),
  ('Boston Fern Plant', 'Nephrolepis exaltata', 'Also known as the sword fern, this variety is frilly, fluffy, with large fronds that are often bright green. They originated in humid forests and swaps and need lots of humidity to thrive.', 'Fern', 2, 2, 1, 'https://s7d1.scene7.com/is/image/terrain/58122755_000_a?$zoom2$'),
  ('Pink Rubber Tree', 'Ficus elastica', 'The strawberry-and-cream colored leaves of the Pink Rubber Tree make it a unique option for any indoor space. This plant grows quickly in ideal conditions and requires bright indirect light to maintain its stylish color.  Rubber Trees are popular ornamental plants that can grow to over 30 meters tall in the right conditions. Its name comes from the milky latex in its leaves which was once used to make natural rubber. Native to east India, in some parts of the country, the roots of the tree are guided over chasms to form natural bridges!', 'Tree', 3, 3, 2, 'https://d38ei4965zsa3u.cloudfront.net/images/products/49faeb5f-c109-4a2a-addb-66d8d2ccb962.jpeg?version=1574925210.48990019800'),
  ('Magenta Triostar', 'Stromanthe sanguinea triostar', 'A striking accent plant with exotic magenta, cream, and green patterned foliage.  This stromathe is Native to the rainforests of Brazil and truly loves jungle-like conditions.  It is a close cousin to the calathea family and shares the tendency for its foliage to curl in on itself during the evening. This movement allows you to enjoy the brightly colored leaves from all angles at all times of the day. Be sure to turn your plant as it ages for full, even growth. Stands out when mixed alongside other greenery. The Triostar prefers prefers medium light and is a great air purifier.', 'Calathea', 3, 3, 2, 'https://d38ei4965zsa3u.cloudfront.net/images/products/76b7cb1b-87ee-4a86-852b-727cdb508b13.jpg'),
  ('Peace Lily', 'Spathiphyllum', 'The Peace Lily is a popular choice for indoor plants because of its white flower-like features and ease of care. Its elegant green leaves are terrific at purifying the air from undesired toxins. Peace Lilies enjoy low to medium light, and express a need for water by sagging their leaves, which perk back up once watered! In ideal conditions the plant will regenerate its flowers forever.', 'Lily', 1, 3, 1, 'https://images.unsplash.com/photo-1593691509543-c55fb32d8de5'),
  ('Neon Pothos', 'Epipremnum aureum', 'The Pothos is widely considered to be among the easiest and most forgiving of plants to care for. It grows vines that can be trimmed or arranged to create a lush mini-jungle, and is a terrific purifier of indoor air.', 'Pothos', 1, 3, 1, 'https://images.unsplash.com/photo-1586883573403-cb7ee339755b'),
  ('Desert Cactus', 'Euphorbia ammak', 'This California-grown Desert Cactus is a rare find. It is strikingly grand in stature and has a bohemian aesthetic that makes it extremely photogenic. This cactus can reach a height of 20 feet in the wild and its whimsical, branching arms make it seem almost human-like. Like most cacti, it likes desert conditions with a lot of light and not a lot of water.', 'Cacti', 2, 5, 3, 'https://images.unsplash.com/photo-1564668848727-0908b6b68ae3'),
  ('Corkscrew rush', 'Juncus effusus Spiralis', 'The young, leafless stems are light green and coiled, with the coils becoming looser with age. They grow in both a horizontal and vertical direction. By winter, the stems become a yellow-brown or tan colour. Flowers are both rare and insignificant in terms of the plant’s appearance. They are yellow-green or light brown.', '', 4, 1, 2, 'https://lh3.googleusercontent.com/proxy/4r36M7rGVqVcLt46wEkCv-bbUIjHKQlY7Yi_-QmY0TflKCWo9Qv8OVqNtD4B1QN045R5Af2cILCUbigIvdo0tidfvRGLzokuMk9JlTo3LGmbPWxghqJEa7MEXQ'),
  ('Pancake Plant', 'Pilea Peperomioides', 'Pilea Peperomioides	Also known as the Chinese money plant, the pancake plant, or the UFO plant, the pilea peperomioides is one of our favorite houseplants because it is fast to grow, low maintenance, and fun to propagate. The coin-shaped leaves also make quite the statement in your home and arrives ready to display in an artful metal container.', '', 2, 3, 2, 'https://s7d1.scene7.com/is/image/terrain/58736398_000_a');



